#define NPROC        64   // 最大进程数
#define NCPU          8   // 最大CPU数
#define NOFILE       16   // 每个进程可打开的文件数
#define NFILE       100   // 系统中可打开的文件总数
#define NINODE       50   // 最大活跃i节点数
#define NDEV         10   // 最大主设备号数
#define ROOTDEV       1   // 文件系统根磁盘的设备号
#define MAXARG       32   // 最大可执行程序参数数
#define MAXOPBLOCKS  10   // 任何文件系统操作最大写入的块数
#define LOGSIZE      (MAXOPBLOCKS*3)   // 磁盘上日志的最大数据块数
#define NBUF         (MAXOPBLOCKS*3)   // 磁盘块缓存的大小
#define FSSIZE       1000   // 文件系统的大小（以块为单位）
#define MAXPATH      128    // 最大文件路径名长度
